//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveGameEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveGameEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable value contains non-numeric characters! Please try again..
        /// </summary>
        public static string BadVariableValueMessage {
            get {
                return ResourceManager.GetString("BadVariableValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file is empty or corrupt! Please specify a different one..
        /// </summary>
        public static string CorruptSaveMessage {
            get {
                return ResourceManager.GetString("CorruptSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving DLL!.
        /// </summary>
        public static string DLLSaveErrorMessage {
            get {
                return ResourceManager.GetString("DLLSaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that the &apos;Edit Mode&apos; is experimental. In some cases, it might make the game crash unexpectedly, or even completely refuse to save to or load from the modified file, not to mention causing tornados in and around Arcadia Bay.
        ///
        ///Variables/Floats: Select a cell (or a range of cells) using the mouse or the arrow keys, and type in the new value. If you accidentally selected the wrong cell(s), then press ESC to cancel the edit.
        ///
        ///Flags/Items: Simply check or uncheck the respective boxes in the table. You ca [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EditModeHelpFirst {
            get {
                return ResourceManager.GetString("EditModeHelpFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables/Floats: Select a cell (or a range of cells) using the mouse or the arrow keys, and type in the new value. If you accidentally selected the wrong cell(s), then press ESC to cancel the edit.
        ///
        ///Flags/Items: Simply check or uncheck the respective boxes in the table. You can use the mouse or the arrow keys and Spacebar. To edit multiple cells at once, select them and press Shift+T (True) of Shift+F (False).
        ///The &quot;true&quot; value in the items table indicates that the item is owned by Chloe, while &quot;false&quot; m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EditModeHelpIconMessage {
            get {
                return ResourceManager.GetString("EditModeHelpIconMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully!.
        /// </summary>
        public static string EditsSuccessfullySavedMessage {
            get {
                return ResourceManager.GetString("EditsSuccessfullySavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTTUTORIAL_kBedtime
        ///BTTUTORIAL_kBedtimeChoices
        ///BTTUTORIAL_kCute
        ///BTTUTORIAL_kCuteChoices
        ///BTTUTORIAL_kDescription
        ///BTTUTORIAL_kE2Reminder
        ///BTTUTORIAL_kE3Reminder
        ///BTTUTORIAL_kFailure
        ///BTTUTORIAL_kPlayground
        ///BTTUTORIAL_kStarted
        ///Seen_BioChloe Price
        ///Seen_BioDamon Merrick
        ///Seen_BioDrew North
        ///Seen_BioEliot Hampden
        ///Seen_BioFrank Bowers
        ///Seen_BioJames Amber + Rose Amber
        ///Seen_BioJoyce Price + David Madsen
        ///Seen_BioMax Caulfield
        ///Seen_BioNathan Prescott
        ///Seen_BioRachel Amber
        ///Seen_BioSera Gearhardt
        ///Seen_Bio [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FlagList {
            get {
                return ResourceManager.GetString("FlagList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BurnerSMSIndex
        ///BurnerSMSOrder_e3_s05_damon_1
        ///BurnerSMSOrder_e3_s05_damon_2
        ///BurnerSMSOrder_e3_s05_damon_3
        ///BurnerSMSOrder_e3_s05_damon_4
        ///BurnerSMSOrder_e3_s05_damon_5
        ///BurnerSMSOrder_e3_s05_damon_6
        ///BurnerSMSOrder_e3_s05_damon_7
        ///BurnerSMSOrder_e3_s05_damon_8
        ///BurnerSMSOrder_e3_s05_damon_9
        ///BurnerSMSOrder_e3_s05_damon_10
        ///BurnerSMSOrder_e3_s05_damon_11
        ///BurnerSMSOrder_e3_s05_damon_12
        ///BurnerSMSOrder_e3_s05_damon_13
        ///BurnerSMSOrder_e3_s05_damon_14
        ///BurnerSMSOrder_e3_s05_damon_15
        ///BurnerSMSOrder_e3_s05_dam [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FloatList {
            get {
                return ResourceManager.GetString("FloatList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/IgelRM/LiS-BtS-Savegame-viewer.
        /// </summary>
        public static string ProjectHomepage {
            get {
                return ResourceManager.GetString("ProjectHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen the following date:
        ///
        ///{0}
        ///
        ///Do you want to proceed with the changes ?.
        /// </summary>
        public static string RewindDateOnlyMessage {
            get {
                return ResourceManager.GetString("RewindDateOnlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A few notes on the Checkpoint Rewind feature:
        ///
        ///1. It has not been extensively tested and may cause unintended consequences. Users are advised to make backups of their data before proceeding further.
        ///
        ///2. If you are on a mid-level checkpoint, then selecting the last item in the checkpoint list will still cause the game to start from the beginning of that point.
        ///
        ///3. If you want to change only the date of the save, don&apos;t touch the checkpoint list at all. To reset the state of the list, click &quot;Load&quot; again..
        /// </summary>
        public static string RewindHelpFirstMessage {
            get {
                return ResourceManager.GetString("RewindHelpFirstMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Load to display the list of available checkpoints. Select the one that you would like to restart from and press Save. You can optionally change the &quot;save date&quot; that is displayed when switching between save slots.
        ///
        ///If you are on a mid-level checkpoint, then selecting the last item in the checkpoint list will still cause the game to start from the beginning of that point.
        ///
        ///If you want to change only the date of the save, don&apos;t touch the checkpoint list at all. To reset the state of the list, click &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RewindHelpIconMessage {
            get {
                return ResourceManager.GetString("RewindHelpIconMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! ALL your progress after the checkpoint specified
        ///below will be lost! The target checkpoint is:
        ///
        ///{0}
        ///{1}
        ///
        ///Are you sure you want to continue?.
        /// </summary>
        public static string RewindProgressLostMessage {
            get {
                return ResourceManager.GetString("RewindProgressLostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes have been successfully written to the save files!
        ///Do you want to do something else?.
        /// </summary>
        public static string RewindSuccessfullySavedMessage {
            get {
                return ResourceManager.GetString("RewindSuccessfullySavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Ctrl+F to search in the table!.
        /// </summary>
        public static string SearchHelpMessage {
            get {
                return ResourceManager.GetString("SearchHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup was successful!.
        /// </summary>
        public static string SuccessfulBackupMessage {
            get {
                return ResourceManager.GetString("SuccessfulBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved edits left! Exit without saving?.
        /// </summary>
        public static string UnsavedEditsWarningMessage {
            get {
                return ResourceManager.GetString("UnsavedEditsWarningMessage", resourceCulture);
            }
        }
    }
}
